test:
  script:
  - python3 -m pip install tox
  - tox -e ALL

run:
  script:
  - python3 setup.py bdist_wheel

deploy:
  only:
    tags
  script:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install setuptools wheel twine
  - python3 setup.py sdist bdist_wheel
  - python3 -m twine upload dist/*

pages:
  script:
  - pip3 install loguru networkx sphinx
  - sphinx-build -W -b html docs docs/_build/html
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

# [testenv:docs]
# basepython = python3.7
# deps = sphinx
# extras = docs
# commands =
#    sphinx-build -W -b html -d {envtmpdir}/doctrees docs docs/_build/html
#    sphinx-build -W -b coverage -d {envtmpdir}/doctrees docs docs/_build/html
#    sphinx-build -W -b doctest -d {envtmpdir}/doctrees docs docs/_build/html
#    python -m doctest README.rst
