test:
  script:
  - tox -e ALL

run:
  script:
  - python3 setup.py bdist_wheel

# pages:
#  script:
#   - pip install sphinx sphinx-rtd-theme
#   - cd doc ; make html
#   - mv build/html/ ../public/
#   artifacts:
#     paths:
#     - public
#   only:
#   - master
